### ISSUE TITLE
Feature Request COUNTDOWN.. [Calendar & Relative Date]

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#16]
**Major Suggestion**
-  I Suggest that Al Chan Need The Coundown Timer Feature... Not Only In "**RELEASING TODAY**" 

And Also the Date IS Too small to see... And I think that Nearsighted People Like Me... Hardly Read The Date... 

And I think that It is More Exciting If You Can See.. How Many days Before your favorite Anime Is Aired.. 

![Screenshot_20200904_230848.jpg](https://user-images.githubusercontent.com/65703094/92254535-9f9c9180-ef03-11ea-9918-4cf8653d8c71.jpg)

RATHER THAN Add Like Anichart.. Countdown..

![Screenshot_20200904_231351.jpg](https://user-images.githubusercontent.com/65703094/92255016-5436b300-ef04-11ea-990b-d1e0e6293be3.jpg)

AND IT IS VERY USEFULL..

- Feature.. SOMETHING LIKE THIS... FILTER BY DAY... 
![Screenshot_20200905_113558.jpg](https://user-images.githubusercontent.com/65703094/92296898-356c0700-ef6c-11ea-9cda-012d2bf98c7c.jpg)

**Mini Suggestion..**
- MAKE the Episode Number slightly Bigger And **Bold**
- When On Hold The +Ep Button... IT WILL POP UP and manually Add Ep

CLICK HERE👇

**[❤️❤️❤️ ](https://user-images.githubusercontent.com/65703094/92258340-420b4380-ef09-11ea-9144-f7e83fda1277.gif)**

**Comment by zend10** [comment]
- Relative date is a good one. I'll make the option to view date with that.

- Bigger font though is doubtful. The airing date font is actually as big as the format right beside it.  It doesn't look appropriate to give it the same size as the title, for aesthetic reason. I think the issue is more of the secondary color from Axiel Blue Theme being not bright enough for you. I think you should consider changing the the secondary color of your list.

- That's the Calendar feature I was planing about in the development plan. I didn't even realize we have that in AniChart before today. :)

- Same as airing date, progress font doesn't need to be bigger and bolder. It has the same size as the title already, just not bold. Consider styling your list or changing the theme. I think it's clear enough on themes with brighter accent color.

- I don't quite understand what does "IT WILL POP UP" mean. What is IT? Please explain.

And I've clicked that. Thanks.

**Comment by ImPudding-tech** [comment]
When Pressed and Hold The +1 Ep.. A SET PROGRESS WILL POP UP.....

**Comment by zend10** [comment]
That Set Progress dialog will pop up if we just click on the progress text beside it. I don't think it's really necessary to add long press action to +1 button to open that Set Progress dialog.

**Comment by ImPudding-tech** [comment]
Oh... THANKS... I DISNT NOTICE THAT... 😅

**Comment by zend10** [comment]
If it has primary color, it can probably be clicked. ;)

**Comment by ImPudding-tech** [comment]
Zend10...
DO YOU HAVE A PLAN MAKING DISCORD..? 

Because i Think Thank Everytime I Have A Question or a Problem.. I always Ask Through Comment... Or create Issue...
. 
If you have Discord Channel Mind if I Join..

**Comment by zend10** [comment]
No Discord server planned for AL-chan unfortunately. You can DM the Twitter account if you have question. If you have suggestions, keep them coming through GitHub issue is fine, don't worry about it.

**Comment by zend10** [comment]
Relative date is implemented on v.1.1.5. Calendar to follow in the next update.

**Comment by zend10** [comment]
Implemented in v.1.1.9.
