### ISSUE TITLE
some 'corrections', bugs and suggestions [Share, UI/UX improvement, View all list]

### ISSUE THREAD

**Issue by Sam-Oak** [zend10/AL-chan#24]
# Corrections

1. **"Share Profile" copies the link instead**.
When i open a user profile, click on the overflow menu and in "Share Profile", the profile link is copied to the clipboard instead of opening the share menu.

2. **Click on "Follows You" to follow**.
If i want to follow a user who already follows me i have to click on "Follows You" because the text "Follow" is overlapped by this other text.

# Bugs

3. **Some problems with the themes**.
**A** • in the white theme, because of the shadow on profile cover, it is hard to see the buttons that are black.
**B** • also, the notification bar is completely white which could be transparent with the cover.
**C** • even changing the theme in the settings, the list remains with the previous theme.

A & B: buttons and notification bar.
![Screenshot_20201003204357](https://user-images.githubusercontent.com/62823895/95004502-543cd800-05c2-11eb-9435-24f5d2f86d5f.jpg)

C: "default theme blue" in "light theme red".
![Screenshot_20201003204417](https://user-images.githubusercontent.com/62823895/95004505-5f900380-05c2-11eb-8f77-13d0c5081d12.jpg)

# Suggestions

1. **Remove "Ch." from the manga list**.
the progress of anime episodes is shown only as "7/12", but the manga chapters are like "Ch. 125 /?".

2. **Remove my score from a series.**:
be able to remove my score for an series if i accidentally put a score before watch/read it.
3. **Remove "Open Media Page" on list editor**:
remove confirmation to open the series info page in Anime/Manga List Editor screen by clicking on the series name.
4. **Search for series in all status on my list**:
it is complicated to search for an anime/manga and switch from "watching" to "Completed (TV)", "TV Short", "OVA", "ONA" etc, just to find it.

~~5. **"Negative" filter**:
if possible, create a way to select an option in Filter (ex. Contry: CHINA) to be filtered from the list and Explore screen, to show all series without it.~~ edit: just saw in twitter that this was added

**Comment by zend10** [comment]
Corrections:
1. Yes, I should show the sharesheet instead.
2. It's intended. I don't want too much stuff cluttering the interface. If you have a nice-looking solution, I will want to see it.

Bugs:
1. I don't believe this is a bug. The shadow from the app is actually white for Light Theme. If you collapse the toolbar, you'll see the icons clearly. From the image you provided, the shadow is from the banner image.
2. It's already pointed out in issue #10 for awhile. I really want to support edge to edge but I have a problem with implementing it.
3. It's intended. If you have ever customized your list, it will stay after you've changed the theme because we wouldn't want our list style get overridden by app theme.

Suggestions:
1. Yes, maybe I'll do that. I'm a bit worried people will get confused which is chapter and which is volume if not specified clearly. What's your thoughts on that?
2. Just set it to 0. It's how AniList does it.
3. Alright, I've been considering it as well.
4. How would you suggest it's done?

**Comment by Sam-Oak** [comment]
Corrections
2. i can only think of putting it below the follow button or above the bio description, but maybe it is better to leave it this way

Bugs
1. ah yes, true. but it’s also hard to see white icons on white banners, putting a shadow behind the icons like twitter would be good? https://imgur.com/a/iNxA0np
3. i see. but now i realized that the anime list remains with the same theme. only the manga list changes

Suggestion
1. i forgot about it because i disabled the volume progress. so maybe, remove that text if you only allow the chapter progress? (btw, you can't hide episode progress on anime list?)
2. I use the 5 star scoring system, so i can only put 1 to 5 stars https://imgur.com/a/YPAjgdp
3.hmm, maybe when you press the search icon, it opens a new screen similar to global search?

anyway, thanks for the hard work

**Comment by zend10** [comment]
Bugs
1. That looks good.
2. Must be because you haven't customized the manga list yet.

Suggestion:
1. I'll think about it.
2. You can swipe all the way to the left to remove all stars.
3. I'm also discussing about it in issue #25. I'll consider making a list to show "All", so that we can search all directly.

**Comment by zend10** [comment]
Will be implemented in the next update:
1. Use share sheet to share
2. Icon with transparent background
3. Remove the text "Ch."
4. "All" list

Implemented in v.1.1.9:
1. Remove dialog to open media.

**Comment by zend10** [comment]
> Will be implemented in the next update:
> 
>     1. Use share sheet to share
> 
>     2. Icon with transparent background
> 
>     3. Remove the text "Ch."
> 
>     4. "All" list
> 
> 
> Implemented in v.1.1.9:
> 
>     1. Remove dialog to open media.

Everything except "All" list is implemented in v.1.2.0. "All" list will be tracked in that other issue so this one can be closed.
