### ISSUE TITLE
Why is there never a review?

### ISSUE THREAD

**Issue by taksumaki** [zend10/AL-chan#4]
I have been watching several anime or manga and the reviews tab always appears blank, I do not understand the reason why this happened, I suppose it will be a failure in the application.

![Screenshot_2020-07-19-16-44-46-846_com zen alchan](https://user-images.githubusercontent.com/56084970/87887108-5d64d280-c9df-11ea-9ebb-1a053b53e08a.jpg)

![Screenshot_2020-07-19-16-47-32-897_com zen alchan](https://user-images.githubusercontent.com/56084970/87887129-99983300-c9df-11ea-855b-62d8a0261fa6.jpg)

**Comment by zend10** [comment]
There's no review there because nobody is writing it.

Here are the links to the website, which also show no review:
https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/reviews
https://anilist.co/manga/81527/Yume-Nikki/reviews

Series that are currently running and series that are not very popular usually have no people writing reviews for them.

For series that do have review, will also show up in the app:
https://anilist.co/anime/477/ARIA-The-ANIMATION/reviews
