### ISSUE TITLE
[Feature Request] Exporting anime and manga lists

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#54]
While there is a feature to import, it would be cool to have an export feature to the app. It will be useful for people who have to sync the list between different platforms or to have a backup.

**Comment by zend10** [comment]
This sounds good actually. Will try.

**Comment by N0D4N** [comment]
I think this shouldnt be feature of mobile app, since it will need to support different platforms. This can be achieved with other tools,  such as https://malscraper.azurewebsites.net/ which supports exporting AniList/MAL/Kitsu lists to MAL-list xml file which then can be imported to AniList/MAL, and probably Kitsu, but im not sure if kitsu supports import from file or only import from existing MAL profile

**Comment by zend10** [comment]
Can vouch for that malscraper. Good tool.
